version: "3.9"
networks:
  service-net:
    driver: bridge
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./wwwroot:/var/www
      - ./work/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./work/nginx/config/conf.d:/etc/nginx/conf.d
      - ./work/nginx/logs:/var/log/nginx
    container_name: webnet
    restart: always
    networks:
      - service-net
  redis:
    build: ./redis
    ports:
      - "6377:6379"
    volumes:
      - ./work/redis/data:/data
      - ./work/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis
    restart: always
    networks:
      - service-net
  php74:
    build: ./php/7.4
    ports:
      - "9074:9000"
    volumes:
      - ./wwwroot:/var/www
      - ./work/php74/config/php.ini:/usr/local/etc/php/php.ini
      - ./work/php74/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./work/php74/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./work/php74/logs:/var/log/php
    container_name: php74
    networks:
      - service-net
  php70:
    build: ./php/7.0
    ports:
      - "9070:9000"
    volumes:
      - ./wwwroot:/var/www
      - ./work/php70/config/php.ini:/usr/local/etc/php/php.ini
      - ./work/php70/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./work/php70/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./work/php70/logs:/var/log/php
    container_name: php70
    networks:
      - service-net
  php54:
    build: ./php/5.4
    ports:
      - "9054:9000"
    volumes:
      - ./wwwroot:/var/www
      - ./work/php54/logs:/var/log/php
      - ./work/php54/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./work/php54/config/php.ini:/usr/local/etc/php/php.ini
    container_name: php54
    networks:
      - service-net
  mysql80:
    build: ./mysql/8.0
    ports:
      - "3380:3306"
    restart: always
    volumes:
      - ./work/mysql80/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
    container_name: mysql80
    networks:
      - service-net
  mysql56:
    build: ./mysql/5.6
    ports:
      - "3356:3306"
    restart: always
    volumes:
      - ./work/mysql56/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
    container_name: mysql56
    networks:
      - service-net
 